services:
  legoorganizer:
    container_name: LEGOOrganizer
    restart: unless-stopped
    build: .
    ports:
      - "3333:3333"
    volumes:
      - .:/app
    env_file:
      - .env
    networks:
      - webproxy
networks:
  webproxy:
    external: true
